//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.CustomerOrder = new HashSet<CustomerOrder>();
            this.QuotePrice = new HashSet<QuotePrice>();
            this.SaleDepot = new HashSet<SaleDepot>();
            this.SaleReturn = new HashSet<SaleReturn>();
        }
    
        public string CusID { get; set; }
        public Nullable<int> CLID { get; set; }
        public string CusName { get; set; }
        public string CusCompany { get; set; }
        public string CusMan { get; set; }
        public string CusDesc { get; set; }
    
        public virtual CustomerLevel CustomerLevel { get; set; }
        public virtual ICollection<CustomerOrder> CustomerOrder { get; set; }
        public virtual ICollection<QuotePrice> QuotePrice { get; set; }
        public virtual ICollection<SaleDepot> SaleDepot { get; set; }
        public virtual ICollection<SaleReturn> SaleReturn { get; set; }
    }
}
