//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduceInDepot
    {
        public ProduceInDepot()
        {
            this.ProduceInDepotDeteil = new HashSet<ProduceInDepotDeteil>();
        }
    
        public string PIDID { get; set; }
        public string DepotID { get; set; }
        public Nullable<System.DateTime> PIDDate { get; set; }
        public Nullable<int> PIDUser { get; set; }
        public Nullable<int> PIDState { get; set; }
        public string PDIDesc { get; set; }
    
        public virtual Depots Depots { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<ProduceInDepotDeteil> ProduceInDepotDeteil { get; set; }
    }
}
