//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDepot
    {
        public SaleDepot()
        {
            this.SaleDepotDetail = new HashSet<SaleDepotDetail>();
            this.SaleReturn = new HashSet<SaleReturn>();
        }
    
        public string SDID { get; set; }
        public string CusID { get; set; }
        public string DepotID { get; set; }
        public Nullable<System.DateTime> SDDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SDState { get; set; }
        public string SDDesc { get; set; }
        public string COID { get; set; }
    
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Depots Depots { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<SaleDepotDetail> SaleDepotDetail { get; set; }
        public virtual ICollection<SaleReturn> SaleReturn { get; set; }
    }
}
