//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockReturn
    {
        public StockReturn()
        {
            this.StockReturnDetail = new HashSet<StockReturnDetail>();
        }
    
        public string KRID { get; set; }
        public string PPID { get; set; }
        public string SIDID { get; set; }
        public string DepotID { get; set; }
        public Nullable<System.DateTime> KRDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> KRState { get; set; }
        public string KRDesc { get; set; }
    
        public virtual Depots Depots { get; set; }
        public virtual ProductLend ProductLend { get; set; }
        public virtual StockInDepot StockInDepot { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<StockReturnDetail> StockReturnDetail { get; set; }
    }
}
