//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.CheckDepot = new HashSet<CheckDepot>();
            this.CustomerOrder = new HashSet<CustomerOrder>();
            this.Devolves = new HashSet<Devolves>();
            this.InOutDepot = new HashSet<InOutDepot>();
            this.Losts = new HashSet<Losts>();
            this.OtherInDepot = new HashSet<OtherInDepot>();
            this.OtherOutDepot = new HashSet<OtherOutDepot>();
            this.PayOffs = new HashSet<PayOffs>();
            this.ProduceInDepot = new HashSet<ProduceInDepot>();
            this.ProduceOutDepot = new HashSet<ProduceOutDepot>();
            this.QuotePrice = new HashSet<QuotePrice>();
            this.SaleDepot = new HashSet<SaleDepot>();
            this.SaleReturn = new HashSet<SaleReturn>();
            this.Splits = new HashSet<Splits>();
            this.StockInDepot = new HashSet<StockInDepot>();
            this.StockReturn = new HashSet<StockReturn>();
            this.Stocks = new HashSet<Stocks>();
            this.UsersRole = new HashSet<UsersRole>();
        }
    
        public int UsersID { get; set; }
        public string UsersName { get; set; }
        public string UserLoginName { get; set; }
        public string UserLoginPwd { get; set; }
        public Nullable<bool> UsersTF { get; set; }
    
        public virtual ICollection<CheckDepot> CheckDepot { get; set; }
        public virtual ICollection<CustomerOrder> CustomerOrder { get; set; }
        public virtual ICollection<Devolves> Devolves { get; set; }
        public virtual ICollection<InOutDepot> InOutDepot { get; set; }
        public virtual ICollection<Losts> Losts { get; set; }
        public virtual ICollection<OtherInDepot> OtherInDepot { get; set; }
        public virtual ICollection<OtherOutDepot> OtherOutDepot { get; set; }
        public virtual ICollection<PayOffs> PayOffs { get; set; }
        public virtual ICollection<ProduceInDepot> ProduceInDepot { get; set; }
        public virtual ICollection<ProduceOutDepot> ProduceOutDepot { get; set; }
        public virtual ICollection<QuotePrice> QuotePrice { get; set; }
        public virtual ICollection<SaleDepot> SaleDepot { get; set; }
        public virtual ICollection<SaleReturn> SaleReturn { get; set; }
        public virtual ICollection<Splits> Splits { get; set; }
        public virtual ICollection<StockInDepot> StockInDepot { get; set; }
        public virtual ICollection<StockReturn> StockReturn { get; set; }
        public virtual ICollection<Stocks> Stocks { get; set; }
        public virtual ICollection<UsersRole> UsersRole { get; set; }
    }
}
